-- V101: Per-candidate disposition recording for forecast batch runs.
--
-- Today, the only trace of why a candidate was skipped (tide mismatch, triage,
-- cache hit, past date, etc.) lives in [BATCH DIAG] log lines — ephemeral and
-- only reachable via SSH. This table persists every candidate's outcome per
-- cycle so the Job Run detail view can reconcile "242 candidates → 163
-- evaluated · 48 hard-constraint · 41 triaged · 2 cached · 1 past-date"
-- without leaving the browser.
--
-- The disposition column is a VARCHAR so adding new categories later (e.g. the
-- reserved SKIPPED_NO_REFRESH_NEEDED for intraday refresh) does not require a
-- schema change — only a code change to the enum.
--
-- location_id is nullable because past-date and cached slots are recorded
-- without performing a location lookup (the briefing carries the name).
-- UNKNOWN_LOCATION dispositions are by definition rows whose name had no
-- matching LocationEntity, so location_id is also null in that case.

CREATE TABLE forecast_run_disposition (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_run_id        BIGINT NOT NULL,
    location_id       BIGINT,
    location_name     VARCHAR(255) NOT NULL,
    evaluation_date   DATE NOT NULL,
    event_type        VARCHAR(20) NOT NULL,
    days_ahead        INTEGER,
    disposition       VARCHAR(40) NOT NULL,
    detail            VARCHAR(500),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Primary lookup: dispositions for a given job run.
CREATE INDEX idx_forecast_run_disposition_job_run
    ON forecast_run_disposition(job_run_id);

-- Secondary lookup: future "show me all triaged in May" analytics + retention prune scans.
CREATE INDEX idx_forecast_run_disposition_disp_created
    ON forecast_run_disposition(disposition, created_at);

-- Register the retention/cleanup job with the dynamic scheduler.
-- Runs daily at 03:30 (after the 03:00 batch run but before backups at 04:00),
-- prunes rows older than 30 days. At ~2k rows/day this caps the table at ~60k.
INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, cron_expression, status)
VALUES ('disposition_cleanup',
        'Forecast Disposition Cleanup',
        'Prunes per-candidate batch disposition records older than 30 days',
        'CRON', '0 30 3 * * *', 'ACTIVE');
