-- V102: Nightly pipeline orchestrator — cycle identity + per-phase observability.
--
-- Replaces the implicit time-buffer coupling between the forecast batch
-- (~01:00, completes in ~10 min) and the daily briefing (~04:00) with an
-- explicit orchestrator that runs the briefing when the batch cycle has
-- actually completed.
--
-- pipeline_run         — one row per orchestrated cycle. Carries cycle
--                        identity and overall lifecycle.
-- pipeline_run_phase   — per-phase status and timing. Lets the Job Run
--                        detail view render the full phase timeline.
-- forecast_batch       — gains pipeline_run_id so the orchestrator can ask
--                        "are all batches for this cycle complete?" via a
--                        single durable query.
--
-- cycle_type accepts a future INTRADAY value (the intraday refresh, when
-- built, reuses this same orchestrator with a different cycle_type and
-- phase set). The phases enumerated below are NIGHTLY's; intraday phases
-- live in code, not in this schema.

CREATE TABLE pipeline_run (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- NIGHTLY today. INTRADAY reserved for the intraday refresh follow-on.
    cycle_type          VARCHAR(20) NOT NULL,
    -- RUNNING / COMPLETED / FAILED
    status              VARCHAR(20) NOT NULL,
    -- Which phase is currently active (FORECAST_BATCH_SUBMIT /
    -- FORECAST_BATCH_WAIT / BRIEFING). Null after completion.
    current_phase       VARCHAR(40),
    -- Human-readable description of what the orchestrator is currently
    -- waiting on, e.g. "forecast batch set (2 of 4 complete)". Surfaces
    -- in the live pipeline run view so a stall is visible at a glance.
    waiting_on          VARCHAR(255),
    trigger_time        TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at        TIMESTAMP WITH TIME ZONE,
    failure_reason      VARCHAR(500),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pipeline_run_status ON pipeline_run(status);
CREATE INDEX idx_pipeline_run_trigger_time ON pipeline_run(trigger_time DESC);

CREATE TABLE pipeline_run_phase (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id     BIGINT NOT NULL,
    phase               VARCHAR(40) NOT NULL,
    -- 1, 2, 3, ... so the UI can render the phases in order.
    sequence_order      INT NOT NULL,
    -- RUNNING / COMPLETED / FAILED
    status              VARCHAR(20) NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at        TIMESTAMP WITH TIME ZONE,
    -- Holds the last waiting_on (for WAIT phase) or a failure reason
    -- (for FAILED phase). Null otherwise.
    detail              VARCHAR(500),
    CONSTRAINT fk_phase_pipeline_run FOREIGN KEY (pipeline_run_id)
        REFERENCES pipeline_run(id) ON DELETE CASCADE
);

CREATE INDEX idx_phase_pipeline_run_seq
    ON pipeline_run_phase(pipeline_run_id, sequence_order);

-- Tag every forecast_batch row created by an orchestrated cycle. Null for
-- ad-hoc (admin) batch submissions that aren't part of an orchestrated
-- cycle — keeps the unrelated paths cleanly distinguishable.
ALTER TABLE forecast_batch
    ADD COLUMN pipeline_run_id BIGINT;

CREATE INDEX idx_forecast_batch_pipeline_run
    ON forecast_batch(pipeline_run_id);
