-- V104: Per-pipeline-run persistence of the best-bet/also-good picks the
-- briefing phase produces.
--
-- This is the value-proving record for the intraday refresh: each cycle
-- snapshots its single Plan A (Best Bet) and single Plan B (Also Good) so
-- consecutive runs can be compared — did the intraday run change the
-- recommendation versus the morning's nightly run? That comparison IS
-- the "do I need to replan?" signal intraday exists to surface.
--
-- One row per pick. Normal cycle persists 1–2 rows (one for rank 1, one
-- for rank 2 when the advisor emits a Plan B). A degenerate "stay home"
-- cycle persists a single rank-1 row with null event/region.
--
-- The pick captures both Claude's qualitative output (headline/detail/
-- confidence) and a numeric snapshot of the region's
-- claudeAverageRating at pick time (drawn from the cached per-location
-- evaluations). The numeric rating is the cross-run comparison primitive:
-- consecutive runs' ratings are directly comparable, where headline
-- prose is not.
--
-- pick_rank is named (not "rank") to avoid SQL reserved-word issues in
-- some dialects.
CREATE TABLE pipeline_run_pick (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_run_id          BIGINT NOT NULL,
    -- 1 = Best Bet (Plan A), 2 = Also Good (Plan B)
    pick_rank                INT NOT NULL,
    -- Pick narrative as emitted by the advisor
    headline                 VARCHAR(500),
    detail                   VARCHAR(1000),
    -- Composite event identifier as the advisor emits it,
    -- e.g. "2026-05-28_sunset" or "2026-05-28_aurora". Parsed parts
    -- below are denormalised so the UI does not need to re-split.
    event_id                 VARCHAR(50),
    event_date               DATE,
    event_type               VARCHAR(20),
    -- Region this pick recommends. May be null for stay-home picks;
    -- aurora picks may reference any region (validation is relaxed for
    -- aurora at advisor level).
    region                   VARCHAR(100),
    -- Claude's qualitative confidence: HIGH / MEDIUM / LOW
    confidence               VARCHAR(20),
    -- Numeric snapshot of the region's claudeAverageRating at the moment
    -- this pick was persisted (1.0–5.0). Null when no cached Claude
    -- scores were available for the (region, date, event_type) at persist
    -- time — in which case the run's rating comparison gracefully degrades
    -- to confidence-level comparison.
    claude_average_rating    DOUBLE PRECISION,
    -- Relationship of a rank-2 pick to the rank-1 pick:
    -- SAME_SLOT (Tier 1) or DIFFERENT_SLOT (Tier 2). Null for rank 1.
    relationship             VARCHAR(20),
    -- CSV of dimensions a rank-2 DIFFERENT_SLOT pick differs by:
    -- subset of "DATE,EVENT,REGION". Null/empty for rank 1 or SAME_SLOT.
    differs_by               VARCHAR(50),
    recorded_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_pick_pipeline_run FOREIGN KEY (pipeline_run_id)
        REFERENCES pipeline_run(id) ON DELETE CASCADE
);

CREATE INDEX idx_pick_pipeline_run ON pipeline_run_pick(pipeline_run_id, pick_rank);
