-- V108: forecast_score — normalised per-component score rows.
--
-- Pass 1 of the forecast-score re-architecture: this table is created
-- ADDITIVE-ONLY. Nothing writes to it yet (dual-write is Pass 2) and
-- nothing reads from it (read migration is Pass 4). It replaces, over
-- several gated passes, the column-per-forecast-type sprawl on
-- forecast_evaluation and the field sprawl inside
-- cached_evaluation.results_json. The serving path is untouched until the
-- dual-write has proven itself via reconciliation.
--
-- Grain: one row per (forecast_type, location, evaluation_date, event_type)
-- — the component grain. The nightly pipeline re-evaluates the same
-- (location, date, event) across cycles, so Pass 2 writers UPSERT against
-- uq_forecast_score_component: latest evaluation wins, matching
-- cached_evaluation semantics. pipeline_run_id is provenance only — never
-- part of the key. It is nullable because sync-path (admin) writes have no
-- pipeline run.
--
-- score is native-scale per type; interpret via forecast_type.scale_max.
-- Only 1–5 types are ever combiner peers; 0–100 types are display products.
--
-- summary is nullable user-facing prose: deterministic types (TIDAL) have
-- none. Raw Claude responses are NOT stored here — api_call_log diagnostics
-- is their home, and only on unhappy paths.

CREATE TABLE forecast_score (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_type_id BIGINT      NOT NULL,
    location_id      BIGINT      NOT NULL,
    evaluation_date  DATE        NOT NULL,
    -- SUNRISE / SUNSET (TargetType). HOURLY exists for wildlife comfort
    -- runs and is never colour-evaluated, so it should not appear here.
    event_type       VARCHAR(20) NOT NULL,
    score            INTEGER     NOT NULL,
    summary          TEXT,
    pipeline_run_id  BIGINT,
    evaluated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_score_forecast_type FOREIGN KEY (forecast_type_id)
        REFERENCES forecast_type (id),
    CONSTRAINT fk_score_location FOREIGN KEY (location_id)
        REFERENCES locations (id),
    CONSTRAINT fk_score_pipeline_run FOREIGN KEY (pipeline_run_id)
        REFERENCES pipeline_run (id),
    CONSTRAINT uq_forecast_score_component
        UNIQUE (forecast_type_id, location_id, evaluation_date, event_type)
);

-- "All components for a location/date" — the Planner-cell shape (Pass 4).
CREATE INDEX idx_forecast_score_location_date
    ON forecast_score (location_id, evaluation_date);

-- "All rows of one type for a date" — the hot-topic / reconciliation shape.
CREATE INDEX idx_forecast_score_type_date
    ON forecast_score (forecast_type_id, evaluation_date);
