-- V115: survivor_atmosphere — the readings half of the unified survivor read surface.
--
-- Stage B of the survivor-surface fix. The atmospheric hot-topic detectors (DUST,
-- SURGE, SNOW_FRESH, SNOW_TOPS) read pre-evaluation readings that, nightly, only
-- ever land on the triaged-out REJECT rows of forecast_evaluation (survivors route
-- to cached_evaluation). They therefore misfire off rejects. This table is the
-- survivor-only carrier for those readings, written at SUBMISSION time (where the
-- AtmosphericData still exists) from the survivor's snapshot — the counterpart to
-- forecast_score (the SCORES half: inversion, sky, tidal, bluebell). Together they
-- back one unified read model; storage stays correctly shaped (scores vs readings),
-- never a single flattened table (which would regrow the V107/V108 sprawl).
--
-- Grain: one row per (location, evaluation_date, event_type). The nightly pipeline
-- re-evaluates the same key across cycles, so writers UPSERT against
-- uq_survivor_atmosphere — latest submission wins, matching forecast_score /
-- cached_evaluation semantics.
--
-- Survivor-by-construction: a row exists only when a survivor is submitted (batch)
-- or evaluated (sync), so a detector reading this table cannot sample rejects.
--
-- All readings nullable: inland locations have no surge; summer has no snow;
-- freezing_level_m is populated year-round (the live plumbing proof). humidity is
-- carried because the SNOW_FRESH query co-returns it for the SNOW_MIST variant.
--
-- Written behind the photocast.survivor-atmosphere.write flag (default true);
-- additive and unread until the Stage 2 read model lands (the forecast_score
-- Pass-1/2 gating discipline).

CREATE TABLE survivor_atmosphere (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id            BIGINT       NOT NULL,
    evaluation_date        DATE         NOT NULL,
    event_type             VARCHAR(20)  NOT NULL,
    aerosol_optical_depth  NUMERIC(6, 3),
    dust                   NUMERIC(7, 2),
    pm2_5                  NUMERIC(7, 2),
    surge_risk_level       VARCHAR(20),
    snow_depth_m           DOUBLE PRECISION,
    freezing_level_m       DOUBLE PRECISION,
    humidity               INTEGER,
    evaluated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_survivor_atmosphere_location FOREIGN KEY (location_id)
        REFERENCES locations (id),
    CONSTRAINT uq_survivor_atmosphere
        UNIQUE (location_id, evaluation_date, event_type)
);

-- "All survivor readings for a date" — the hot-topic detector scan shape.
CREATE INDEX idx_survivor_atmosphere_date
    ON survivor_atmosphere (evaluation_date);
