-- V119: travel_day — user-declared "away" date ranges that gate the overnight
-- forecast batch.
--
-- The single operator of this instance commutes to London on a roster that
-- changes week to week; on those days no photography happens at the configured
-- locations, so any Claude forecast whose TARGET date falls inside a travel
-- range is pure spend with no payoff. Each row is one inclusive [start_date,
-- end_date] range with an optional note ("London — work"). ForecastTaskCollector
-- reads these at collection time and drops candidates whose target date lands in
-- a range (disposition SKIPPED_TRAVEL_DAY), so the batch still runs and still
-- covers non-travel days — only the useless target dates are skipped.
--
-- Ranges are ad-hoc, not recurring: travel is not fixed, so the operator adds
-- and removes ranges each week via Manage → Operations → Travel Days. No seed
-- rows — an empty table is the dormant, no-op state (every date is workable).

CREATE TABLE travel_day (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date  DATE         NOT NULL,
    end_date    DATE         NOT NULL,
    note        VARCHAR(200),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_travel_day_range CHECK (end_date >= start_date)
);

-- "Is :date inside any range" — the single-date containment scan the gate runs.
CREATE INDEX idx_travel_day_range ON travel_day (start_date, end_date);
