-- V123: coastal hot-topic enrichment — a sea-state (marine) source plus the numeric
-- surge the storm-surge model already computes but never persisted.
--
-- Two additive, fully-nullable changes back the enriched KING_TIDE / SPRING_TIDE /
-- STORM_SURGE pills:
--
-- 1. marine_wave — a new table holding the significant wave height (Hs), swell, and
--    wave direction sampled at the aligned high-water time, one row per coastal
--    (location, date, event). Written once per briefing cycle from the Open-Meteo
--    Marine API — the hot-topic strategies never call an API, they only read this
--    table. The sea-state band ("very rough") is DERIVED from Hs at render time via
--    a single shared classifier and is deliberately NOT stored, so the king/spring
--    pill and the storm-surge pill can never disagree on the same Hs. Grain matches
--    the survivor surface: (location_id, evaluation_date, event_type).
--
-- 2. survivor_atmosphere gains the numeric surge/wind that StormSurgeService already
--    computes on AtmosphericData but which was dropped after write (only the
--    surge_risk_level String was kept). Without these the storm-surge pill cannot
--    show "surge +0.6 m · wind WSW 38 mph". All nullable — inland rows have none.

CREATE TABLE marine_wave (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id               BIGINT       NOT NULL,
    evaluation_date           DATE         NOT NULL,
    event_type                VARCHAR(20)  NOT NULL,
    significant_wave_height_m DOUBLE PRECISION,
    swell_wave_height_m       DOUBLE PRECISION,
    wave_direction_deg        INTEGER,
    evaluated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_marine_wave_location FOREIGN KEY (location_id)
        REFERENCES locations (id),
    CONSTRAINT uq_marine_wave
        UNIQUE (location_id, evaluation_date, event_type)
);

-- "All wave samples for a date" — the coastal hot-topic detector scan shape.
CREATE INDEX idx_marine_wave_date
    ON marine_wave (evaluation_date);

-- Numeric surge/wind for the storm-surge facts line (previously only the risk band was kept).
ALTER TABLE survivor_atmosphere ADD COLUMN surge_total_m DOUBLE PRECISION;
ALTER TABLE survivor_atmosphere ADD COLUMN surge_wind_speed_ms DOUBLE PRECISION;
ALTER TABLE survivor_atmosphere ADD COLUMN surge_wind_direction_deg DOUBLE PRECISION;
