-- Cloud verification: score a past forecast against reanalysed (observed) cloud.
--
-- Every threshold the colour-scoring rules turn on is a CLOUD claim — solar-horizon low cloud
-- >60% blocks light, a 20pp build means the event-time snapshot understates cloud, a 30pp drop
-- at 226km means a thin strip. Cloud claims are machine-checkable against Open-Meteo's archive,
-- so they can be validated without a photographer recording an outcome.
--
-- This matters because actual_outcome is empty: the cloud-approach veto currently forces
-- rating 1-2 on roughly one evaluation in seven, and nothing has ever verified it.
--
-- TWO points are verified per evaluation, because the forecast makes two different claims:
--   * the SOLAR HORIZON point (113 km along the solar azimuth) answers "is there a gap for the
--     low sun to shine through" — low cloud there is the blocker;
--   * the OBSERVER point answers "is there a canvas overhead for that light to land on" — mid
--     and high cloud there are the screen.
-- Verifying only the horizon would leave the canvas half of every forecast unchecked.
--
-- One row per verified forecast_evaluation. Nullable observed columns so an attempt that found
-- no archive data is recorded rather than retried forever.

CREATE TABLE cloud_verification (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forecast_evaluation_id    BIGINT           NOT NULL UNIQUE,

    -- The solar-horizon point actually sampled (derived from the evaluation's own azimuth).
    horizon_sample_lat        DOUBLE PRECISION NOT NULL,
    horizon_sample_lon        DOUBLE PRECISION NOT NULL,

    -- Analysed cloud at the solar horizon: does the gap exist?
    horizon_low_cloud         INTEGER,
    horizon_mid_cloud         INTEGER,
    horizon_high_cloud        INTEGER,

    -- Analysed cloud overhead at the observer: is there a canvas?
    observer_low_cloud        INTEGER,
    observer_mid_cloud        INTEGER,
    observer_high_cloud       INTEGER,

    observed_at               TIMESTAMP,
    verified_at               TIMESTAMP        NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_cloud_verification_evaluation
        FOREIGN KEY (forecast_evaluation_id) REFERENCES forecast_evaluation (id) ON DELETE CASCADE
);

-- The backfill anti-joins on this FK to find unverified evaluations; the report joins on it.
CREATE INDEX idx_cloud_verification_evaluation
    ON cloud_verification (forecast_evaluation_id);
