-- V151: topic_daily_log — the Coming up model's future food (plan P7).
--
-- Starts a durable, append-only presence/intensity log: one row per (topic_type, date, region_id).
-- Nothing reads this table yet — no scoring branches on it, no UI renders it. It exists so that,
-- after ~90 days of rows, a later phase can replace today's config-fallback rarity (inversions:
-- no unbiased population exists yet, D4) and interim magnitude buckets with observed rates, and so
-- band-transition hysteresis (D4's deferred rule) has a per-night `band` to read back.
--
-- Keyed on region_id, NOT region name — the V145 precedent (§ "region_id, never region name")
-- applies here for the same reason: `daily_briefing_cache`/`cached_evaluation`/
-- `briefing_region_snapshot` were all name-keyed and V137 had to clean up after a rename.
-- ON DELETE CASCADE matches V145's region_drive_time: a log row for a deleted region describes a
-- region that no longer exists, and unknown is the safe direction there, not wrong.
--
-- `present`/`intensity`/`landed_on_window` are written nightly by TopicDailyLogJob (one row per
-- candidate topic per region, for YESTERDAY, from whichever store is least triage-biased for that
-- topic — documented per topic in the job's Javadoc). `band` stays NULL for now: it is the
-- prior-band store the deferred hysteresis rule needs (D4's "band column... after which band
-- assignment becomes SurpriseScore.bandOf(bits, priorBand)"), and no phase writes it yet.
--
-- Append-only, no pruning — a UNIQUE constraint enforces "one row" per key so a re-run (a job
-- re-trigger, a restart mid-run) cannot silently double-count an arrival later.
CREATE TABLE topic_daily_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_type        VARCHAR(20) NOT NULL,
    log_date          DATE NOT NULL,
    region_id         BIGINT NOT NULL REFERENCES regions(id) ON DELETE CASCADE,
    present           BOOLEAN NOT NULL,
    intensity         NUMERIC(10, 3),
    landed_on_window  BOOLEAN,
    band              VARCHAR(20),
    logged_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_topic_daily_log UNIQUE (topic_type, log_date, region_id)
);

-- The only query shape a future census/rarity read needs: every row for one topic across a
-- trailing window, ordered by date. The unique constraint's own index already serves an
-- exact-key lookup, so this is additive for the range scan alone.
CREATE INDEX idx_topic_daily_log_type_date ON topic_daily_log (topic_type, log_date);

-- Seed the nightly job. 04:40 is free: the occupied CRON slots as of this migration are
-- tide_refresh (02:00 Mon), briefing_model_comparison (05:00), refresh_token_cleanup (03:00),
-- near_term_batch_evaluation (03:00/15:00, PAUSED), aurora_batch_evaluation (03:30, PAUSED),
-- disposition_cleanup (03:30), intraday_forecast_refresh (14:00), sky_rating_eval (03:00 Mon,
-- PAUSED), cloud_verification_backfill (hourly :20), drive_time_refresh (02:40),
-- region_drive_time_refresh (03:10), grid_cell_backfill (03:10). The old daily_briefing row that
-- once held 04:00/14:00/22:00 was hard-deleted by V103, so nothing else touches hour 4 at all;
-- 04:40 sits clear of every neighbour above and below it. Runs after the last briefing build
-- (14:00) and well clear of the 03:xx cluster, so it never competes with the jobs most likely to
-- still be running when the night's data is read.
INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type,
                                  cron_expression, status)
VALUES ('topic_daily_log',
        'Topic Daily Log',
        'Logs presence and intensity for the candidate Coming-up topics (Saharan dust, cloud '
            || 'inversions, spring/king tides, storm surge, snow, aurora, noctilucent cloud) '
            || 'across every region for the previous day. Append-only history feeding a later '
            || 'phase''s observed rarity and band-hysteresis rules — nothing reads it yet.',
        'CRON',
        '0 40 4 * * *',
        'ACTIVE');
