-- V158: inversion score for every place — carry the deterministic inversion likelihood
-- calculator's 0-10 score onto the survivor surface.
--
-- InversionScoreCalculator already runs for every inversion-eligible candidate (elevation
-- >= 200m and overlooks_water) inside ForecastService.fetchWeatherAndTriage, before either
-- triage check and before the survivor_atmosphere write — but that score lived only on the
-- in-memory AtmosphericData and was never persisted for a triaged-out or Gate-4-stood-down
-- candidate; only a completed Claude evaluation's echo of it reached forecast_score.INVERSION.
-- That left the InversionHotTopicStrategy silent for exactly the places the "record conditions
-- for every place" change (Phase 1, V115-era, owner decision 2026-09-30) was built to cover.
--
-- Owner decision 2026-09-30 (Phase 2): the inversion hot topic and the Coming up "Valley
-- inversions" condition now read this deterministic score for every eligible place, without
-- waiting on Claude. No feature switch. Bluebell remains the named exception (no deterministic
-- substitute exists for it) and is unaffected by this migration.
--
-- Additive and fully nullable, mirroring V124's temperature column on the same table: a row
-- for an ineligible location (elevation < 200m, or not overlooking water) simply never gets a
-- score here, exactly as InversionScoreCalculator.calculate is never invoked for it today.
ALTER TABLE survivor_atmosphere ADD COLUMN inversion_score DOUBLE PRECISION;
