-- Unique email constraint (nulls allowed for existing admin accounts)
CREATE UNIQUE INDEX IF NOT EXISTS idx_app_user_email ON app_user(email);

-- Email verification tokens (follows refresh_token pattern)
CREATE TABLE email_verification_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64)  NOT NULL UNIQUE,
    user_id    BIGINT       NOT NULL,
    expires_at TIMESTAMP    NOT NULL,
    verified   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_evt_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
