-- Model test run: one row per triggered A/B/C test across regions
CREATE TABLE model_test_run (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at       TIMESTAMP    NOT NULL,
    completed_at     TIMESTAMP,
    duration_ms      BIGINT,
    target_date      DATE         NOT NULL,
    target_type      VARCHAR(10)  NOT NULL,
    regions_count    INT          NOT NULL DEFAULT 0,
    succeeded        INT          NOT NULL DEFAULT 0,
    failed           INT          NOT NULL DEFAULT 0,
    total_cost_pence INT          NOT NULL DEFAULT 0
);

-- Model test result: one row per region/location/model evaluation
CREATE TABLE model_test_result (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_run_id           BIGINT       NOT NULL,
    region_id             BIGINT       NOT NULL,
    region_name           VARCHAR(255) NOT NULL,
    location_id           BIGINT       NOT NULL,
    location_name         VARCHAR(255) NOT NULL,
    target_date           DATE         NOT NULL,
    target_type           VARCHAR(10)  NOT NULL,
    evaluation_model      VARCHAR(10)  NOT NULL,
    rating                INT,
    fiery_sky_potential    INT,
    golden_hour_potential  INT,
    summary               VARCHAR(1000),
    prompt_sent           TEXT,
    response_json         TEXT,
    duration_ms           BIGINT,
    cost_pence            INT          NOT NULL DEFAULT 0,
    succeeded             BOOLEAN      NOT NULL DEFAULT FALSE,
    error_message         VARCHAR(500),
    created_at            TIMESTAMP    NOT NULL,
    CONSTRAINT fk_mtr_test_run FOREIGN KEY (test_run_id) REFERENCES model_test_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_mtr_region   FOREIGN KEY (region_id)   REFERENCES regions(id),
    CONSTRAINT fk_mtr_location FOREIGN KEY (location_id) REFERENCES locations(id)
);
