-- Astro conditions: nightly observing quality scores for dark-sky locations.
-- Template-scored (no Claude), available to all users.
CREATE TABLE astro_conditions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id            BIGINT NOT NULL REFERENCES locations(id),
    forecast_date          DATE NOT NULL,
    run_timestamp          TIMESTAMP NOT NULL,
    stars                  INT NOT NULL,
    cloud_modifier         DOUBLE PRECISION NOT NULL,
    visibility_modifier    DOUBLE PRECISION NOT NULL,
    moon_modifier          DOUBLE PRECISION NOT NULL,
    fog_capped             BOOLEAN NOT NULL DEFAULT FALSE,
    cloud_explanation      VARCHAR(200),
    visibility_explanation VARCHAR(200),
    moon_explanation       VARCHAR(200),
    summary                VARCHAR(500),
    nautical_dusk_utc      TIMESTAMP,
    nautical_dawn_utc      TIMESTAMP,
    mean_cloud_pct         INT,
    mean_visibility_m      INT,
    moon_illumination_pct  DOUBLE PRECISION,
    moon_altitude_deg      DOUBLE PRECISION,
    moon_phase             VARCHAR(30),
    UNIQUE (location_id, forecast_date)
);

CREATE INDEX idx_astro_conditions_date ON astro_conditions (forecast_date);
