-- V68: Dynamic scheduler job configuration table + seed data for 5 scheduled jobs

CREATE TABLE scheduler_job_config (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_key             VARCHAR(50) NOT NULL UNIQUE,
    display_name        VARCHAR(100) NOT NULL,
    description         VARCHAR(500),
    schedule_type       VARCHAR(20) NOT NULL,
    cron_expression     VARCHAR(100),
    fixed_delay_ms      BIGINT,
    initial_delay_ms    BIGINT,
    status              VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    last_fire_time      TIMESTAMP WITH TIME ZONE,
    last_completion_time TIMESTAMP WITH TIME ZONE,
    config_source       VARCHAR(200),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed the 5 scheduled jobs with their current default schedules

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, cron_expression, status)
VALUES ('tide_refresh', 'Tide Refresh', 'Refreshes 14 days of tide extremes from WorldTides for all coastal locations', 'CRON', '0 0 2 * * MON', 'ACTIVE');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, cron_expression, status)
VALUES ('daily_briefing', 'Daily Briefing', 'Refreshes the daily briefing — weather and tide conditions across all enabled colour locations', 'CRON', '0 0 4,14,22 * * *', 'ACTIVE');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, fixed_delay_ms, initial_delay_ms, status, config_source)
VALUES ('aurora_polling', 'Aurora Polling', 'Polls NOAA SWPC for aurora activity and drives the notification lifecycle', 'FIXED_DELAY', 300000, 60000, 'ACTIVE', 'aurora.enabled');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, fixed_delay_ms, initial_delay_ms, status, config_source)
VALUES ('met_office_scrape', 'Met Office Scrape', 'Scrapes the Met Office space weather forecast page for aurora triage context', 'FIXED_DELAY', 3600000, 300000, 'ACTIVE', 'aurora.enabled');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, fixed_delay_ms, initial_delay_ms, status)
VALUES ('run_progress_cleanup', 'Run Progress Cleanup', 'Removes stale forecast run progress entries older than 30 minutes', 'FIXED_DELAY', 300000, 300000, 'ACTIVE');
