-- V72: Anthropic Batch API tracking table + scheduler seed rows for batch evaluation jobs

CREATE TABLE forecast_batch (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anthropic_batch_id  VARCHAR(100) NOT NULL UNIQUE,
    batch_type          VARCHAR(30) NOT NULL,
    status              VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    request_count       INT NOT NULL DEFAULT 0,
    succeeded_count     INT,
    errored_count       INT,
    submitted_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at            TIMESTAMP WITH TIME ZONE,
    expires_at          TIMESTAMP WITH TIME ZONE,
    last_polled_at      TIMESTAMP WITH TIME ZONE,
    error_message       VARCHAR(1000)
);

-- Scheduler seed rows for batch evaluation jobs (start disabled — opt-in feature)

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, cron_expression, status)
VALUES ('near_term_batch_evaluation',
        'Near-Term Batch Evaluation',
        'Submits forecast evaluations (SHORT_TERM locations) to the Anthropic Batch API for cost-efficient async processing',
        'CRON', '0 0 3,15 * * *', 'PAUSED');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, cron_expression, status, config_source)
VALUES ('aurora_batch_evaluation',
        'Aurora Batch Evaluation',
        'Submits aurora location evaluations to the Anthropic Batch API overnight',
        'CRON', '0 30 3 * * *', 'PAUSED', 'aurora.enabled');

INSERT INTO scheduler_job_config (job_key, display_name, description, schedule_type, fixed_delay_ms, initial_delay_ms, status)
VALUES ('batch_result_polling',
        'Batch Result Polling',
        'Polls the Anthropic Batch API every 60 s for completed batches and writes results to the evaluation cache',
        'FIXED_DELAY', 60000, 30000, 'ACTIVE');
