-- Waitlist email collection for when the early-access registration cap is reached.
CREATE TABLE waitlist_email (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    submitted_at TIMESTAMP NOT NULL DEFAULT NOW()
);
