package com.gregochr.goldenhour.service;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link GitInfoService}.
 */
class GitInfoServiceTest {

    @Test
    @DisplayName("init loads git.properties and exposes all fields")
    void init_loadsAllFields() {
        // GitInfoService.init() reads from classpath "git.properties".
        // We test by constructing and calling init() directly — the test classpath
        // has a git.properties via the build plugin or a test resource.
        GitInfoService service = new GitInfoService();
        service.init();

        // If git.properties exists on the test classpath (generated by the plugin),
        // all fields should be populated. If not, available=false.
        // We test both paths gracefully.
        if (service.isAvailable()) {
            assertThat(service.getCommitHash()).isNotEmpty();
            assertThat(service.getCommitAbbrev()).isNotEmpty();
            assertThat(service.getBranch()).isNotEmpty();
            // commitDate may be null if format not parseable, but hash should be set
        } else {
            // Plugin didn't generate git.properties on this classpath — verify graceful fallback
            assertThat(service.getCommitHash()).isEmpty();
            assertThat(service.getCommitAbbrev()).isEmpty();
            assertThat(service.getBranch()).isEmpty();
            assertThat(service.getCommitDate()).isNull();
        }
    }

    @Test
    @DisplayName("defaults are safe when git.properties is missing")
    void defaults_whenNoGitProperties() {
        GitInfoService service = new GitInfoService();
        // Don't call init() — simulates missing file scenario

        assertThat(service.isAvailable()).isFalse();
        assertThat(service.getCommitHash()).isEmpty();
        assertThat(service.getCommitAbbrev()).isEmpty();
        assertThat(service.getBranch()).isEmpty();
        assertThat(service.getCommitDate()).isNull();
        assertThat(service.isDirty()).isFalse();
    }
}
