package com.gregochr.goldenhour.service;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Builds the database a developer's existing {@code backend/data/goldenhour.mv.db} looks like to
 * Ask: a {@code job_run} table whose {@code run_type} is the native H2 {@code ENUM} Hibernate
 * created <em>before</em> {@code RunType.ASK} and {@code ASK_READY} existed (the fifteen values of
 * commit {@code a66a3171}, the one before the engine landed).
 */
final class LocalH2OldSchemaFixtures {

    /** The pre-Ask {@code RunType} values, as the old commit declared them. */
    static final String OLD_RUN_TYPES = "'VERY_SHORT_TERM','SHORT_TERM','LONG_TERM','WEATHER','TIDE',"
            + "'LIGHT_POLLUTION','BRIEFING','BRIEFING_BEST_BET','BRIEFING_GLOSS','AURORA_EVALUATION',"
            + "'AURORA_GLOSS','BLUEBELL_GLOSS','SCHEDULED_BATCH','BATCH_NEAR_TERM','BATCH_FAR_TERM'";

    private LocalH2OldSchemaFixtures() {
    }

    /**
     * Creates a new H2 file database holding the old {@code job_run} table.
     *
     * @return the JDBC URL of the file database
     * @throws IOException  if the temporary directory cannot be created
     * @throws SQLException if the table cannot be created
     */
    static String oldSchemaFileDatabase() throws IOException, SQLException {
        Path dir = Files.createTempDirectory("ask-old-local-db");
        dir.toFile().deleteOnExit();
        String url = "jdbc:h2:file:" + dir.resolve("goldenhour");
        try (Connection c = DriverManager.getConnection(url, "sa", "");
                Statement s = c.createStatement()) {
            s.execute("create table job_run (id bigint generated by default as identity primary key, "
                    + "run_type enum(" + OLD_RUN_TYPES + ") not null)");
        }
        return url;
    }
}
